name: Dev-Build
on: [push]
jobs:
  build:
    if: "! contains(toJSON(github.event.commits.*.message), '[ci skip]')"
    runs-on: ubuntu-20.04
    container:
      image: openjdk:17-jdk
    steps:
      - run: echo "Setup ğŸ‘·â€"
      - uses: actions/checkout@v3.0.0
      - uses: gradle/wrapper-validation-action@v1.0.4
      - run: chmod +x ./gradlew
      - run: ./gradlew setup
      - run: echo "Tests ğŸ§ª"
      - run: ./gradlew :forge:test --tests "org.bukkit.*"
      - run: ./gradlew :forge:test --tests "org.craftbukkit.*"
      - run: echo "Build ğŸ "
      - run: ./gradlew installerJar
        env:
          STABLE_BUILD: 0
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v3.0.0
        with:
          name: Builds
          path: projects/magma/build/libs/*installer*.jar
